version: "3"

services:
  web:
    build:
      context: '.'
      args:
        uid: ${UID}
    container_name: app-car
    environment:
      - APACHE_RUN_USER=#${UID}
      - APACHE_RUN_GROUP=#${UID}
    image: webdevops/php-apache:alpine-php7
    ports:
      - "4500:80"
      - "3000:3000"
    hostname: appcar.dev
    volumes:
      - .:/var/www/html
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:80"
    environment:
      MYSQL_ROOT_PASSWORD: root

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"
    volumes:
      - ./uploads.ini:/usr/local/etc/php/conf.d/php-phpmyadmin.ini
